### ISSUE TITLE
"wepy build -o web" case error

### ISSUE THREAD

**Issue by tolerance-go** [wepyjs/wepy-weui-demo#15]
/usr/local/lib/node_modules/wepy-cli/lib/web/index.js:354
        wpys.forEach(function (wpy, i) {
             ^

TypeError: wpys.forEach is not a function
    at Object.compile (/usr/local/lib/node_modules/wepy-cli/lib/web/index.js:354:14)
    at /usr/local/lib/node_modules/wepy-cli/lib/web/index.js:235:34
    at Array.forEach (<anonymous>)
    at Object.toWeb (/usr/local/lib/node_modules/wepy-cli/lib/web/index.js:227:28)
    at /usr/local/lib/node_modules/wepy-cli/lib/compile.js:364:37
    at Array.forEach (<anonymous>)
    at Object.build (/usr/local/lib/node_modules/wepy-cli/lib/compile.js:362:19)
    at Command.module.exports (/usr/local/lib/node_modules/wepy-cli/lib/bin/wepy-build.js:12:21)
    at Command.listener (/usr/local/lib/node_modules/wepy-cli/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/local/lib/node_modules/wepy-cli/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/wepy-cli/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/wepy-cli/lib/bin/wepy.js:35:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)

**Comment by Gcaufy** [comment]
try alpha version. 
在alpha版本中我修复了一系列转web的问题
```
npm install wepy-cli@1.7.2-alpha3 -g
```

**Comment by lyle-w** [comment]
Same issue here, and now it fixed with 1.7.2-alpha3.
